#!/usr/bin/env bash
# hermes-bridge setup — installs the bridge from this skill into ~/.hermes/bridge/
# and registers it as a local MCP server so this Hermes's toolset picks it up.
#
# Re-run any time to update the bridge files; the unit is left alone on rerun.
set -euo pipefail

SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${HERMES_BRIDGE_HOME:-$HOME/.hermes/bridge}"
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
PY="${HERMES_PY:-~/.hermes/hermes-agent/venv/bin/python}"

echo "==> Installing hermes-bridge"
echo "    source:  $SKILL_DIR"
echo "    dest:    $DEST"
echo

# ---- 1. figure out the user's tailnet IP ----
if command -v tailscale >/dev/null 2>&1 && tailscale status >/dev/null 2>&1; then
  DEFAULT_BIND=$(tailscale ip -4 2>/dev/null | head -1)
  echo "Detected tailnet IP: $DEFAULT_BIND"
else
  DEFAULT_BIND="100.x.x.x"
  echo "Tailscale not available — defaulting to $DEFAULT_BIND (edit peer_config.toml later)."
fi

# ---- 2. copy files into dest ----
mkdir -p "$DEST" "$DEST/approvals/pending" "$DEST/approvals/audit" "$DEST/shared_inbox" "$DEST/snapshots" "$DEST/systemd"

cp "$SKILL_DIR/hermes_bridge.py"  "$DEST/hermes_bridge.py"
cp "$SKILL_DIR/approvals.py"      "$DEST/approvals.py"
cp "$SKILL_DIR/hermes-bridge.service" "$DEST/systemd/hermes-bridge.service"
cp "$SKILL_DIR/inbox.template.md" "$DEST/shared_inbox/inbox.md"

# peer_config.toml — only write if missing (don't clobber user edits)
if [[ ! -f "$DEST/peer_config.toml" ]]; then
  if [[ -f "$SKILL_DIR/peer_config.toml" ]]; then
    sed "s/100.x.x.x/$DEFAULT_BIND/" "$SKILL_DIR/peer_config.toml" > "$DEST/peer_config.toml"
    echo "Wrote $DEST/peer_config.toml with bind_host=$DEFAULT_BIND"
  fi
fi

# ---- 3. auto-generate allowlist.yaml from peer_config.toml ----
BIND_HOST=$(grep '^bind_host' "$DEST/peer_config.toml" | sed 's/.*= *"\(.*\)"/\1/')
PORT=$(grep '^port' "$DEST/peer_config.toml" | sed 's/.*= *\([0-9]\+\).*/\1/')

cat > "$DEST/allowlist.yaml" <<EOF
# Auto-generated by hermes-bridge setup.sh from peer_config.toml.
# Edit peer_config.toml and rerun setup.sh to change vault roots.

default_allow:
  - vault_read         # read files under allowed roots
  - session_search     # search past Hermes conversations
  - inbox_read         # read shared coordination inbox
  - agent_ask          # route a prompt through the Hermes agent loop

allowed_vault_roots:
$(awk '/allowed_roots = \[/,/\]/' "$DEST/peer_config.toml" \
    | grep '"' \
    | sed -E 's/.*"([^"]+)".*/  - \1/')

# Anything else (vault_write, send_message, ha_call_service, etc.)
# falls through to the approval gate.
EOF

# ---- 4. systemd unit (with the right path baked in) ----
cat > "$DEST/systemd/hermes-bridge.service" <<EOF
[Unit]
Description=Hermes bridge — tailnet-only MCP gateway for cloud assistant
After=network-online.target tailscaled.service
Wants=network-online.target

[Service]
Type=simple
Environment=HERMES_BRIDGE_HOME=$DEST
ExecStart=$PY $DEST/hermes_bridge.py --host $BIND_HOST --port $PORT
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=hermes-bridge
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=$DEST

PrivateTmp=true
RestrictSUIDSGID=true
RestrictNamespaces=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_NETLINK AF_UNIX

[Install]
WantedBy=default.target
EOF

# ---- 5. register the bridge as a local MCP server (this Hermes picks it up) ----
if [[ -x "$HERMES_HOME/hermes-agent/venv/bin/hermes" ]]; then
  if ! "$HERMES_HOME/hermes-agent/venv/bin/hermes" mcp list 2>/dev/null | grep -q "^hermes-bridge"; then
    echo
    echo "==> Registering hermes-bridge as a local MCP server"
    "$HERMES_HOME/hermes-agent/venv/bin/hermes" mcp add \
      --url "http://$BIND_HOST:$PORT/mcp" \
      --connect-timeout 15 \
      hermes-bridge || echo "  (registration failed — run manually after fixing)"
  fi
fi

# ---- 6. install telegram resolver + cron for approval flow ----
mkdir -p "$HERMES_HOME/scripts"
mkdir -p "$DEST/scripts"
for f in telegram_resolver.sh _resolve_chunk.py; do
  if [[ -f "$SKILL_DIR/scripts/$f" ]]; then
    cp "$SKILL_DIR/scripts/$f" "$HERMES_HOME/scripts/$f"
    cp "$SKILL_DIR/scripts/$f" "$DEST/scripts/$f"
    chmod +x "$HERMES_HOME/scripts/$f" "$DEST/scripts/$f"
  fi
done
echo
echo "==> Installed telegram resolver at $HERMES_HOME/scripts/telegram_resolver.sh + _resolve_chunk.py"
if "$HERMES_HOME/hermes-agent/venv/bin/hermes" cron list 2>/dev/null | grep -q "hermes-bridge-approvals"; then
  echo "  Cron 'hermes-bridge-approvals' already scheduled."
else
  "$HERMES_HOME/hermes-agent/venv/bin/hermes" cron create \
    --name hermes-bridge-approvals \
    --schedule '*/1 * * * *' \
    --script telegram_resolver.sh \
    --no-agent \
    --deliver local \
    --prompt 'hermes-bridge telegram approval resolver' 2>&1 | head -10
fi

echo
echo "==> Done."
echo
echo "Next steps:"
echo "  1. Review peer_config.toml and allowlist.yaml in $DEST"
echo "  2. Smoke test: $PY $DEST/hermes_bridge.py --host $BIND_HOST --port $PORT"
echo "     then in another shell: HERMES_BRIDGE_URL=http://$BIND_HOST:$PORT $PY $SKILL_DIR/scripts/smoke.py"
echo "  3. Install systemd unit (optional):"
echo "       systemctl --user link $DEST/systemd/hermes-bridge.service"
echo "       systemctl --user daemon-reload"
echo "       systemctl --user enable --now hermes-bridge.service"